apiVersion: v1
data:
  authsources.php: |
    <?php

    $config = array(

        'admin' => array(
            'core:AdminPassword',
        ),

        'example-userpass' => array(
            'exampleauth:UserPass',
            'user1:user1pass' => array(
                'uid' => array('1'),
                'eduPersonAffiliation' => array('group1'),
                'email' => 'user1@example.com',
                'cn' => 'User One',
            ),
            'user2:user2pass' => array(
                'uid' => array('2'),
                'eduPersonAffiliation' => array('group2'),
                'email' => 'user2@example.com',
                'cn' => 'User Two',
            ),
        ),

    );
  saml20-sp-remote.php: |
    <?php
    $metadata['https://sp.example.com/shibboleth'] = array(
        'AssertionConsumerService' => 'http://sp.example.com:8080/Shibboleth.sso/SAML2/POST',
        'SingleLogoutService' => 'http://sp.example.com:8080/Shibboleth.sso/SLO/Redirect',
        'sign.logout' => true,
    );
kind: ConfigMap
metadata:
  name: idp-config
