apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - host: sp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sp-service
            port:
              number: 8080
  - host: idp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: idp-service
            port:
              number: 8080
