apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-deployment
  labels:
    app: sp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sp
  template:
    metadata:
      labels:
        app: sp
    spec:
      containers:
      - name: sp
        image: demo-sp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sp-service
spec:
  selector:
    app: sp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
